Fix AttributeError: module 'plistlib' has no attribute 'readPlist'
moul/alfred-workflow-gauth pull request #36
Opened 2022-10-26 05:37 UTC by georgyjose

2025-02-12 12:54 UTC, aik099 requested changes

2025-02-12 12:54 UTC, aik099 commented on src/alfred.py
> +preferences = plistlib.load(file)
Please do it like this:

```python
with open('info.plist', 'rb') as f:
    preferences = plistlib.load(f)
```

This way, a temporary variable used for accessing the file won’t be exposed to anyone who includes this file.

2025-02-12 12:54 UTC, aik099 commented
This PR solves Python 3.10 compatibility and inability to use this workflow with Alfred 5.

2025-02-12 13:00 UTC, georgyjose commented on src/alfred.py
> +preferences = plistlib.load(file)
Awesome suggestion. Made the changes @aik099

2025-02-12 14:53 UTC, aik099 commented
@georgyjose , it appears, that #38 with a similar change was already merged (I can see that code in https://github.com/moul/alfred-workflow-gauth/blob/master/src/alfred.py#L22).

The issue with is that https://github.com/moul/alfred-workflow-gauth/blob/master/Google%20Authenticator.alfredworkflow file wasn't rebuilt after the merge.

I recommend the following approach:

1. please close this PR as a duplicate (even though you've submitted it before the merged PR) of a #38
2. backup workflow version you're using (via Export function of Alfred) just in case
2. please submit a new PR with a change to `Google Authenticator.alfredworkflow` file, that is created like so:
   * make sure the `master` branch of your fork is up to date with the `master` branch of this repo
   * create a PR branch
   * run the `bundle.sh --install` command
3. confirm, that produced workflow can be installed properly and works
4. submit new PR


My apologies for the confusion with my previous PR review comment.

2025-02-12 14:58 UTC, aik099 commented
If possible attach a diff from the contents of the current and new `Google Authenticator.alfredworkflow` files in a comment. The `*.alfredworkflow` file is just a zip file. Just change file extension > unzip > compare.

2025-02-12 14:58 UTC, aik099 approved these changes

2025-02-13 05:39 UTC, closed without merging

2025-02-13 10:15 UTC, aik099 commented
@georgyjose , would you be doing that other PR?

2025-02-14 05:02 UTC, georgyjose commented
Thanks for the detailed explanation @aik099. Here's the PR with the updated `Authenticator.alfredworkflow` file https://github.com/moul/alfred-workflow-gauth/pull/46.